kind: pipeline
type: docker
name: deploy

steps:
- name: deploy
  image: mwienk/docker-lftp
  environment:
    USERNAME:
      from_secret: ftp-esenjin-username
    PASSWORD:
      from_secret: ftp-esenjin-password
    HOST:
      from_secret: shelter-host
  commands:
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd cila.camelia-studio.org/moisson-rouge; mirror -Rpnevvv --parallel=10 --exclude .git/"